content:
  - { path: /, key: homepage, label: Home, showInNav: true }
  - { path: /about, key: about, label: About, showInNav: true }
  - { path: /services, key: services, label: Services, showInNav: true }
  - { path: /contact, key: contact, label: Contact, showInNav: true }
  - { path: /donate, key: donate, label: Donate, showInNav: true }
  - { path: /credits, key: credits, label: Credits, showInNav: false }
  - { path: /portfolio, key: portfolio, label: Portfolio, showInNav: false }
#  - { path: /portfolio/workshop, key: workshop, label: Workshop, showInNav: false}
portfolio:
  - { path: /workshop, key: workshop}
  - { path: /cp, key: cp}
description: Ten-Forward is a small nonprofit with big dreams
logos:
  white: /images/logos/10F_Logo_Full_White.png
  black: /images/logos/10F_Logo_Full_Black.png
  yellow: /images/logos/10F_Logo_Full_Yellow.png
  green: /images/logos/10F_Logo_Full_Green.png
digitalOcean: { url: 'https://digitalocean.com', imgUrl: '/images/uploads/DO_Logo_icon_black.png'}
social:
  insta: { url: 'https://www.instagram.com/10forwardslash/', faIcon: 'instagram'}
  linkedin: { url: 'https://www.linkedin.com/company/ten-forward', faIcon: 'linkedin-in'}
  twitter: { url: 'https://twitter.com/10forwardslash', faIcon: 'twitter'}
  facebook: { url: 'https://facebook.com/10forwardslash', faIcon: 'facebook-f'}
  medium: { url: 'https://medium.com/@10forwardslash', faIcon: 'medium'}
repo: https://github.com/tenforwardslash/ten-forwardslash
title: Ten-Forward
titleHome: Ten-Forward | The next generation of nonprofits
url: https://peaceful-gates-58e765.netlify.com/
