content:
  - { path: /, key: homepage, label: Home }
  - { path: /about, key: about, label: About }
  - { path: /services, key: services, label: Services }
  - { path: /contact, key: contact, label: Contact }
  - { path: /donate, key: donate, label: Donate }
description: Ten-Forward is a small nonprofit with big dreams
logoUrl: https://peaceful-gates-58e765.netlify.com/images/10f-square.png
social:
  insta: { url: 'https://www.instagram.com/10forwardslash/', faIcon: 'instagram'}
  linkedin: { url: 'https://www.linkedin.com/company/ten-forward', faIcon: 'linkedin-in'}
  twitter: { url: 'https://twitter.com/10forwardslash', faIcon: 'twitter'}
  medium: { url: 'https://medium.com/@10forwardslash', faIcon: 'medium'}
repo: https://github.com/tenforwardslash/ten-forwardslash
title: Ten-Forward
titleHome: Ten-Forward | The next generation of nonprofits
url: https://peaceful-gates-58e765.netlify.com/
