url: https://peaceful-gates-58e765.netlify.com/

title: Ten-Forward

repo: https://github.com/tenforwardslash/ten-forwardslash

titleHome: Ten-Forward | The next generation of nonprofits

description: Ten-Forward is a small nonprofit with big dreams

content:
  - path: /
    key: homepage
    label: Home

  - path: /about
    key: about
    label: About

  - path: /services
    key: services
    label: Services

  - path: /contact
    key: contact
    label: Contact

  - path: /donate
    key: donate
    label: Donate