title: how we support
servicesDesc: >-
  Your nonprofit deserves every resource for success. Our nonprofit wants to be
  that resource.


  Through workshops, consultations, and product research & development,
  Ten-Forward works side-by-side with your organization to identify how
  technology can be best leveraged to serve your mission.
serviceSections:
  - anchorId: consulting
    content: >
      We get it. Investing in new tech feels over-the-top when what you’re doing
      now works. But what if you could streamline your operation?

      Ten-Forward brings world-class technology solutions within reach for your
      nonprofit. Our donors allow us to keep costs low for you. And our extreme
      know-how allows us to partner with you to solve your most frustrating
      problems. 


      We can provide short- or long-term engagements in the following spaces: 

        - data management 
        - systems integration 
        - website development 
        - WordPress custom theme development 
        - application development  
        - infrastructure management

      Have something else in mind? Reach out and we’ll explore solutions
      together. If we can’t help you, we’ll do our best to find someone who
      can. 
    image: /images/uploads/max.png
    name: Consulting
    tagline: Hire experts
  - anchorId: workshops
    content: >-
      Lacking training resources? You’re not alone. Nonprofits regularly
      underutilize the tech they have because of the [prohibitive costs of
      training](https://www.salesforce.org/nonprofit/nonprofit-trends-report/).

      Our affordable, user-friendly workshops empower your organization to put
      the software you’re already using to work so you can focus on your
      specialty—making the world better.


      We currently provide training in WordPress and look forward to adding more
      topics that benefit your organization. [Let us know](/contact) what topics
      would provide the most impact.
    image: /images/uploads/gandalf-lay.png
    name: Workshops
    tagline: Learn skills and save money
  - anchorId: product
    content: >
      Your nonprofit exists in a unique environment that necessitates tools
      built with your needs in mind. You need meaningful, long-lasting
      solutions, and products that are not only within your price range but that
      can adapt to your varied use cases. 


      Ten-Forward is applying a rigorous customer interview process with the
      help of Customer Illuminated to nail down which nonprofit pain points can
      be best mitigated by software solutions. 

      Follow us on Medium and sign up for our newsletter to stay tuned! 
    image: /images/uploads/max.png
    name: Product Research & Development
    tagline: |
      Discover your needs
