backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "public/images/uploads"
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Title Tagline, name: titleTagline, widget: string}
          - label: "CTA Button"
            name: "ctaButton"
            widget: "object"
            fields:
              - {label: "Button Text", name: "ctaButtonText", widget: "string"}
              - {label: "Button Link", name: "ctaButtonLink", widget: "string"}
          - {label: Elevator Pitch, name: elevatorPitch, widget: markdown}
          - {label: Elevator Pitch Image, name: elevatorPitchImage, widget: image}
          - {label: CTA Image, name: ctaImage, widget: image}
          - {label: CTA One, name: ctaOne, widget: string}
          - label: Homepage Blocks
            name: blocks
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: image, widget: image}
              - {label: Path, name: path, widget: text}
          - {label: CTA Two, name: ctaTwo, widget: string}
      - label: "About Page"
        name: "about"
        file: "content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Mission, name: mission, widget: markdown}
          - {label: Vision, name: vision, widget: markdown}
          - {label: History, name: history, widget: markdown}
          - {label: About Title, name: aboutTitle, widget: string}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Biography, name: bio, widget: markdown}
          - label: Board
            name: board
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Image, name: image, widget: image, required: false}
              - {label: Biography, name: bio, widget: markdown, required: false}
      - label: "Services Page"
        name: "services"
        file: "content/services.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Services Description, name: servicesDesc, widget: markdown}
          - label: Services Sections
            name: serviceSections
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Tagline, name: tagline, widget: text}
              - {label: Anchor ID, name: anchorId, widget: string}
              - {label: Content, name: content, widget: markdown}
              - {label: Image, name: image, widget: image}
      - label: "Contact Page"
        name: "contact"
        file: "content/contact.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: string}
          - {label: Footer, name: footer, widget: markdown}
          - {label: Location, name: location, widget: map }
      - label: "Donate Page"
        name: "donate"
        file: "content/donate.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: content, widget: markdown}
          - {label: Legal Disclaimer, name: disclaimer, widget: markdown}
      - label: "Credits Page"
        name: "credits"
        file: "content/credits.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: content, widget: markdown}
      - label: "Portfolio"
        name: "portfolio"
        file: "content/portfolio.yml"
        fields:
          - label: Portfolio Overview Title
            name: overview
            widget: string
          - label: Single Portfolio
            name: singlePortfolio
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Content, name: content, widget: markdown}
