backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "public/images/uploads"
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Title Tagline, name: titleTagline, widget: string}
          - label: "CTA Button"
            name: "ctaButton"
            widget: "object"
            fields:
              - {label: "Button Text", name: "ctaButtonText", widget: "string"}
              - {label: "Button Link", name: "ctaButtonLink", widget: "string"} //TODO: this can take in validation field to check for valid url
          - {label: CTA One, name: ctaOne, widget: string}
          - label: Homepage Blocks
            name: blocks
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: image, widget: image}
         - {label: CTA Two, name: ctaTwo, widget: string}

      - label: "About Page"
        name: "about"
        file: "content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Services Page"
        name: "services"
        file: "content/services.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}
      - label: "Contact Page"
        name: "contact"
        file: "content/contact.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}
      - label: "Donate Page"
        name: "donate"
        file: "content/donate.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}